if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

brew_share="${HOMEBREW_PREFIX:-/opt/homebrew}/share"

[[ -r "$brew_share/powerlevel10k/powerlevel10k.zsh-theme" ]] &&
  source "$brew_share/powerlevel10k/powerlevel10k.zsh-theme"
[[ -r "$brew_share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] &&
  source "$brew_share/zsh-autosuggestions/zsh-autosuggestions.zsh"
[[ -r "$brew_share/zsh-history-substring-search/zsh-history-substring-search.zsh" ]] &&
  source "$brew_share/zsh-history-substring-search/zsh-history-substring-search.zsh"

autoload -Uz compinit
compinit -d "${ZDOTDIR:-$HOME}/.zcompdump"

source "$HOME/.config/zsh/common.zsh"

alias view="nvim -R"

[[ -r "$brew_share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] &&
  source "$brew_share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

unset brew_share
